services:
  - type: web
    name: vidsto-api
    env: node
    buildCommand: npm install
    startCommand: pwd && ls -la && if [ -d "server" ]; then ls -la server/ && node server/index.js; else echo "Server directory not found!" && find . -name "index.js" -type f; fi
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

