services:
  - type: web
    name: vidsto-api
    env: node
    buildCommand: npm install && mkdir -p data temp/videos temp/images uploads/featured-videos logs
    startCommand: mkdir -p data temp/videos temp/images uploads/featured-videos logs && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

