services:
  - type: web
    name: vidsto-api
    env: node
    buildCommand: npm install
    startCommand: ls -la && pwd && ls -la server/ && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

